### ISSUE TITLE
Error running example code

### ISSUE THREAD

**Issue by gjuoun** [lumeland/pug#5]
I try to run the example code from readme.

deno version: 1.20.6

```
error: Uncaught Error: Filename not set!
    throw new Error("Filename not set!");
          ^
    at compileBody (https://cdn.jsdelivr.net/gh/lumeland/pug@0.1.2/mod.ts:120:11)
    at compile (https://cdn.jsdelivr.net/gh/lumeland/pug@0.1.2/mod.ts:317:18)
    at file:///home/gjuoun/Code/deligenius/view-engine/src/pug.ts:20:12

```

How to reproduce:
```ts
import * as pug from "https://raw.githubusercontent.com/lumeland/pug/v0.1.2/mod.ts"

const template = `h1#title Pug - node template engine #{state}`// const template = `p.text Hello World!`

const result = pug.render(template, { state: "awesome" })

console.log(result);
```

Is this a bug?

**Comment by oscarotero** [comment]
Mmm, yes. There was a bug that require to set always a filename in the options.
It's fixed now. Use the latest version (v0.1.3). Thanks!
